name: LMC Build Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system tools
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip mpv dpkg-dev

      - name: Install Python deps
        run: |
          pip3 install -r requirements.txt --user

      - name: Prepare build folder
        run: |
          mkdir -p pkg/usr/bin
          cp lmc.py pkg/usr/bin/lmc
          chmod +x pkg/usr/bin/lmc

      - name: Build DEB package
        run: dpkg-deb --build pkg lmc.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lmc-deb
          path: lmc.deb
